language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --dev

script:
  - phpunit
  - vendor/bin/phpcs --standard=PSR2 --sniffs='-PSR2.Namespaces.NamespaceDeclaration' --report=summary -np Sniffs/
  - vendor/bin/phpcs --standard=ruleset.xml --report=summary -np Sniffs/
